### PR TITLE
Fix CI/CD pipeline

### PR DESCRIPTION
**Pull request by hax0rbana-adam**
It looks like there are linter errors that are stopping the CI/CD from running on all branches, so I thought I'd take a shot at trying to fix them.

This builds on !965 since that's the MR where I was trying to make the CI/CD green. I didn't commit it over there because I didn't want to force these changes to be accepted with the logo change.

### CODE REVIEW

**Comment by hax0rbana-adam** [comment]
I guess not, Bitrise is still failing nearly instantly. I think the issue is in the Bitrise workflow configuration. I had to change mine to get it to get past the new Java 17 requirement, like so:

1. In Bitrise, go to a pipeline that is failing ([example](https://app.bitrise.io/build/82c7a4ba-72e5-4650-86eb-08880dfcb581))
2. If you're logged in, you should see an Edit workflow button. Click that.
3. On the left, click on the Plus button above Git Clone Repository
4. Search for Java, and click Set Java Version
5. Change Java version (under Input variables) to 17

The changes in this branch are also required, but the errors that are being fixed won't appear until the pipeline can get past the current error ("error: invalid source release: 17").

**Comment by n8fr8** [comment]
THanks, we'll work on getting bitrise fixed up again.

**Comment by meenbeese** [comment]
I will also try to help this get resolved faster. Can you rebase on master so everything is up-to-date @hax0rbana-adam ? I want to take a look on what the actual problem is that the applied changes cannot fix.

**Comment by hax0rbana-adam** [comment]
I have rebased on the default branch, and I think I even did so correctly this time.

**Comment by meenbeese** [comment]
Thanks! It looks like there is a mismatch in the Java version we use.

```
> Task :intentintegrator:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':intentintegrator:compileDebugJavaWithJavac'.
> error: invalid source release: 17
```

Plus, things are broken starting from #903,  as Bitrise checks passed [before](https://app.bitrise.io/app/0e76c31b8e7e1801). Could you try to revert said PR and see if my hypothesis is true or not?

**Comment by syphyr** [comment]
No need to revert, just change here to 17.
https://github.com/guardianproject/orbot/blob/5457cf127d3be36f295ef611b458da81196263fc/.github/workflows/android.yml#L22

**Comment by hax0rbana-adam** [comment]
I updated the java version in .github/workflows/android.yml, but I still think the change need to be made [in the bitrise UI](https://github.com/guardianproject/orbot/pull/971#issuecomment-1701891526).

**Comment by n8fr8** [comment]
Will review this week

**Comment by n8fr8** [comment]
fixed now... had to add the bitrise step to set java sdk to 17

**Pull request merged**
