### PR TITLE
Dev fix boot vpn issue

### PR DESCRIPTION
**Pull request by n8fr8**
a number of important small changes to address issues of Orbot VPN not starting on boot properly

### CODE REVIEW

**Comment by syphyr** [comment]
The first hunk from 368fbe1aebfee2f93131e331c0bcc2750111eca5 needs to be rebased against the master branch.

It should be:

```
@@ -55,6 +55,7 @@ import java.util.concurrent.Executors;
 
 import static org.torproject.android.service.OrbotConstants.ACTION_START;
 import static org.torproject.android.service.OrbotConstants.ACTION_START_VPN;
+import static org.torproject.android.service.OrbotConstants.ACTION_START_ON_BOOT;
 import static org.torproject.android.service.OrbotConstants.ACTION_STOP;
 import static org.torproject.android.service.OrbotConstants.ACTION_STOP_VPN;
 
```

**Comment by syphyr** [comment]
This chain does not apply cleanly to master branch.  It says there are no conflicts, but there are.

**Comment by syphyr** [comment]
368fbe1aebfee2f93131e331c0bcc2750111eca5 needs to be rebased against master and pushed over again

**Comment by n8fr8** [comment]
rebased against master

**Pull request merged**
