### PR TITLE
Fix missing symbols

### PR DESCRIPTION
**Pull request by syphyr**
Fixes "one file for constants, not 3"

### CODE REVIEW

**Comment by syphyr** [comment]
Rebased after "see last commit..." to fix app-mini and app-tv

**Comment by syphyr** [comment]
@bitmold these changes are still needed to fix additional missing symbols

**Comment by bitmold** [comment]
I realized I didn't commit those, I committed them after but didn't see your PR

**Comment by syphyr** [comment]
> I realized I didn't commit those, I committed them after but didn't see your PR

you still missed some. I just restored the branch.

**Comment by syphyr** [comment]
app-mini and app-tv still need fixing

**Comment by syphyr** [comment]
@bitmold please re-open

**Comment by bitmold** [comment]
My mistake, thank you

**Pull request merged**
