### PR TITLE
Fix bottom sheet button cut on Tablet

### LINKED ISSUE #876: UI: Button cut off choosing connection type in landscape mode
When choosing the connection type, the connect button is cut off on bottom of screen in landscape mode.

Screenshot_20230412-203027

### PR DESCRIPTION
**Pull request by meenbeese**
<table>
    <tr>
        <th>Before</th>
        <th>After</th>
    </tr>
    <tr>
        <td>
</td>
        <td>
</td>
    </tr>
    <tr>
        <td>
</td>
        <td>
</td>
    </tr>
    <tr>
        <td>
</td>
        <td>
</td>
    </tr>
</table>

Fixes #876

### CODE REVIEW

**Comment by bitmold** [comment]
How does this look + feel on phones?

**Comment by meenbeese** [comment]
> How does this look + feel on phones?

I had accidentally broken the mobile UI a bit, but it should be fixed now. If you look at the mobile screenshots I just added, the changes are minimal except for the bottom sheet height being reduced a bit. I don't know why this happened, yet it looks better in my opinion. We had a lot of wasted space there.

**Comment by syphyr** [comment]
Looks good now on my tablet.  Thanks for this!  One suggestion is that `R.string.secure_your_connection_subtitle` should be centered.

**Comment by meenbeese** [comment]
I'm glad it works. I already wanted to improve, maybe even rewrite, some parts of the UI anyway. I can hopefully fix the alignment of the subtitle then.

**Comment by syphyr** [comment]
I tried fixing the alignment and have it mostly working.  But, I'm stuck.  It works, but on initial startup the text is displayed twice.  After I hit connect and then disconnect, then it works as expected.  But, I really cant figure out why the text is displayed twice on startup.  Can you help?  It's like 99%.
https://github.com/syphyr/orbot/commit/70390b1fff7e4000497c806f5fa32b646c251c28

**Comment by syphyr** [comment]
This commit above also fixes `tvSubtitle` being defined twice in several places.

**Comment by meenbeese** [comment]
Hmmm, on first look I don't understand why you are duplicating `tvSubtitle` with a new `secSubtitle` and a new `Textview`. You should be able to use the existing one and make your modifications there. Because yours also has other visibility and it is not centered.

How the duplication looks:

**Comment by syphyr** [comment]
On my device, `tvSubtitle` is not being centered although `tvTitle` is.  But you are correct, adding an additional variable is not the correct way to fix this.  For now, I have just fixed the problem by setting the visibility to `GONE`.

BTW, There is an addition location where the connect button is not in the correct position on my table.
1) Choose how to connect
2) Obfs4
3) Solve captcha
4) Connect button is not correct

**Comment by syphyr** [comment]
I fixed the rest of the buttons here:
https://github.com/syphyr/orbot/commit/117401116ff96777c7fee6ad2fae8aac810ce487

**Comment by syphyr** [comment]
Here are some screen shots of the fixed UI after my additional changes:

Screenshot_20240127-222111

Screenshot_20240127-222132

Screenshot_20240127-222151

**Comment by syphyr** [comment]
I've also added another commit to make all the buttons the same shape.
https://github.com/syphyr/orbot/commit/8271453f35818e74c5e594b99376540181acb348

**Comment by syphyr** [comment]
additional screenshots with buttons the same shape as the rest of the UI.

Screenshot_20240127-230510

Screenshot_20240127-230540

**Comment by meenbeese** [comment]
These changes look promising. Can you combine all of them in a separate PR where I can provide better feedback and see if anything is missing? These are much needed changes to improve Orbot's UI I think.

**Comment by syphyr** [comment]
Done https://github.com/guardianproject/orbot/pull/1076

**Comment by bitmold** [comment]
Closing here !

**Pull request closed without merging**
