### PR TITLE
Align and format cancel/connect buttons

### PR DESCRIPTION
**Pull request by syphyr**
This PR is built off of @meenbeese's work to align the cancel/connect buttons for tablets.  It also changes the shape of the buttons to match the rest of the UI.

### CODE REVIEW

**Comment by bitmold** [comment]
Wow great, could you throw up some screenshots here please though

**Comment by syphyr** [comment]
Screenshots:

Screenshot_20240128-224605

Screenshot_20240128-224620

Screenshot_20240128-224634

**Comment by meenbeese** [comment]
The screenshots look good, but there is clearly too much bottom margin on the second and third one. Can you bring the buttons down like in the first screenshot?

**Comment by bitmold** [comment]
I can do that, since there's a few other UI things like the title being indented that I want to fix...

**Pull request merged**
