### PR TITLE
Tor Status Reworking 

### PR DESCRIPTION
**Pull request by bitmold**
This makes `OrbotService` follow the status updates from `TorService`, basically removing a lot of vestigial code from the time when `TorService` didn't exist and was a part of `OrbotService`.

In doing so, this fixes the issues reported in #637 and #638 in which Orbot, through the `Intent` logic in netcipher, won't report an `ON` status if it is already running. 

This also removes vestigial code from handling an old + unused start intent in `OrbotMainActivity`. 

I created a simple netcipher app to test this functionality: https://github.com/bitmold/OrbotIntentTest 
You can use that app to start Tor with netcipher. When you start Orbot with it, each status update is logged. When Orbot already has a tor connection, if you press the button in that app a 2nd, 3rd, etc time `ON` is logged.  

I tested this code with that app pretty extensively, as well as trying to weed out any corner case scenarios when Orbot starts on boot. Issues with the notification lock still exist, however with this new code the app UI will at least update to say that Tor is active (though the notification is still broken per #621 )

This code also removes a pretty annoying bug where when you kill Orbot via the main menu, the icon will disappear, reappear and then disappear for a final time. 

PS: @syphyr if you're looking to help with more Orbot testing here I'd definitely appreciate that :)

### CODE REVIEW

**Comment by bitmold** [comment]
Been using this throughout the day and there are a few more tweaks that need to be made here

The newnym notification command opens the app and also there are occasional crashes in the UI with starting and stopping that i believe are a regression. Will post here as these get addressed .....

**Comment by bitmold** [comment]
@n8fr8 this is looking good to me now, curious how your testing will go...

**Comment by syphyr** [comment]
When I stop the tor service by selecting the onion, the screen says "Orbot is shutting down".  But it seems like it should eventually says that it "is shut down".

**Comment by bitmold** [comment]
I don't experience this issue anymore @syphyr - @n8fr8 would you also be able to have a look at this with the latest changeset ..

**Comment by bitmold** [comment]
# No, it's still occurring... I'll fix this when I can :'(

**Comment by bitmold** [comment]
Actually this was a **very** simple fix, I was able to get it in today. Should be good to go as far as I can see!

**Pull request merged**
