### PR TITLE
Ensure ICMPV6 packets are not routed

### LINKED ISSUE #1008: Orbot is leaking ICMP traffic on Android
**Describe the Bug**
After testing with termux and orbot, it has been established that ICMP  traffic is being leaked with Orbot 
**To Reproduce**
Install Termux, establish the vpn tunnel on orbot and run ping google.com on Termux. 

for UDP nc -vz -u 8.8.8.8 443
possibly leaking UDP?

image

image
image

- Device: Pixel 8 Pro
- OS: GrapheneOS Android 14
- Version: Orbot for Android 17.1.1 BETA 2 (tor 0.4.7.8)

### PR DESCRIPTION
**Pull request by syphyr**
Fixes "for #1008 manually ensure ICMP packets are not routed or bypassed"

Fixes #1008

### CODE REVIEW

**Comment by meenbeese** [comment]
Please add `Fixes #1008` to the description to actually close the issue when the PR is merged.

**Review by meenbeese — APPROVED** [review]

**Comment by syphyr** [comment]
> Fixes #1008

Added to description

**Comment by meenbeese** [comment]
> Added to description

What I meant was the PR description, sorry for any confusion on my part.
Said issue should appear here on the sidebar when done correctly:
Screenshot 2023-11-04 160628

**Comment by syphyr** [comment]
> > Added to description
> 
> What I meant was the PR description, sorry for any confusion on my part. Said issue should appear here on the sidebar when done correctly: Screenshot 2023-11-04 160628

Edited PR description as well

**Pull request merged**
