### PR TITLE
Vector image of the Orbot logo for the launcher

### LINKED ISSUE #581: icon is blurry
Hi, the icon is blurry on my Android 11. My app version is 16.4.1, which is the latest version on f-droid. Is it a bug?

### PR DESCRIPTION
**Pull request by hax0rbana-adam**
- Fixes issue #958 about the new logo being confusing / undesirable
- Make launcher logo match the icon in the F-Driod and Google Play stores
- Uses vector based art to scale to different screen sizes
- I believe this will also resolve #581 and #397

Because Android vector graphics do not render in GitHub, here's an image showing the updated icon:

orbot-no-shadow-deep-purple-background_small

### CODE REVIEW

**Comment by meenbeese** [comment]
Does this address #581 as well?

**Comment by hax0rbana-adam** [comment]
> Does this address #581 and #397 as well?

Yes, I believe so. I was able to reproduce the issue #581 on an Android 11 device and v16.4.1 of Orbot from F-Droid and the launcher icon is slightly blurry. Issue #397 doesn't specify what version the reporter was using, but they explicitly say that and adaptive icon would fix this. As far as I can tell this vector format is the only type of icon that will adapt to various screen sizes.

Neither issue specifies whether it is the launcher icon or some other icon in the application, so it is possible they are reporting an issue with some other (or some additional) icon. If they are referring to an icon other than the launcher, this change will not resolve the issue, but it will get us one step closer. Whatever icon needs updated could be replaced with a [VectorDrawable](https://developer.android.com/develop/ui/views/graphics/vector-drawable-resources) and it'll be sharp at any resolution.

**Comment by meenbeese** [comment]
> As far as I can tell this vector format is the only type of icon that will adapt to various screen sizes.

Nice! Thanks for taking a step to fix this.

> Neither issue specifies whether it is the launcher icon or some other icon in the application

I think it is safe to assume that they are both talking about the launcher icon, as that would be what one assumes without explicit mentioning. Otherwise, they would have probably mentioned what icon it is.

Again, thanks for implementing this as I remember vector icons being the recommended ones for Android launchers for solving various reasons described in said issues.

**Comment by brianSchanbacher** [comment]
The new launcher icon looks really clean. A lot of the negative feedback in #958 seems dubious.

**Comment by meenbeese** [comment]
> The new launcher icon looks really clean. A lot of the negative feedback in #958 seems dubious.

As I agree with you, maybe the shadow can also be removed too while we are at it @hax0rbana-adam ? It looks ancient and outdated imo, what do you think?

**Comment by brianSchanbacher** [comment]
> As I agree with you, maybe the shadow can also be removed too while we are at it @hax0rbana-adam ? It looks ancient and outdated imo, what do you think?
> 
> Modern app icons tend to rely less on shadows but more on contrasting colors and backgrounds to differentiate the main subject on the icon

Good feedback, I hadn't noticed the shadow, but you are right. There isn't a single app on my homescreen w/ a shadow.

**Comment by hax0rbana-adam** [comment]
> As I agree with you, maybe the shadow can also be removed too while we are at it @hax0rbana-adam ? It looks ancient and outdated imo, what do you think?

Yeah, I think it'd look fine without the shadow. I was trying to make it match the logos that are on the Google Play and F-Droid app stores.

Conveniently, since it's a vector graphic and not a PNG/GIF/JPG, removing the shadow is just a matter of removing the "shadow" path (the section pasted below). :smiley: Feel free to remove it.

Here's what it looks like rendered without the shadow:

orbot-no-shadow

Also if you want to change the shades of purple to make it pop more, I'd be fine with that too. Again, I was trying to be faithful to the logo that everyone recognizes. Changing the fillColor on the Outline to 4f0063 give a deep purple version that looks better in my opinion. It increases the contrast and makes it easier to see. Here's the rendered version (also without the shadow):

orbot-no-shadow-deep-purple-background

**Comment by meenbeese** [comment]
> I think we need a mascot. Not only logo. Why just not use https://github.com/guardianproject/orbot/blob/865c5c475c09354943b3486e026d7aeac1d2ac96/app/src/main/ic_launcher-playstore.png ?

I understand that you want to express your opinions about the app icon but please cut back on the unnecessary noise you are creating on this thread. You already explained it once and that is enough, writing a message 3 times won't help your cause. @TimoLready

**Comment by meenbeese** [comment]
> Here's what it looks like rendered without the shadow:
Thanks for removing the shadow! It already looks so much better.
> 
> Also if you want to change the shades of purple to make it pop more, I'd be fine with that too. Again, I was trying to be faithful to the logo that everyone recognizes. Changing the fillColor on the Outline to 4f0063 give a deep purple version that looks better in my opinion. It increases the contrast and makes it easier to see. Here's the rendered version (also without the shadow):

Btw using a more popping color is a good idea too that didn't immediately occur to me. I think it makes a lot of sense to make minor tweaks as needed while keeping the base familiar and recognizable.

These are the improvements that are hard to make but also yield a great result. That said, the color is a bit too popping for me and hurts my eyes ever so slightly. We could consider toning it down by making it just a little darker?

What do you guys think?

**Comment by brianSchanbacher** [comment]
@meenbeese I understand where you are coming from. On my screen the sample is rendering at almost 15x15cm and at that size I agree. When I scale the image down to something that Is more indicative of "app icon size" I think the contrast and pop is good.

That being said if we want to rework the colors completely, I'd suggest the following palettes for the "onion" and "purple" colors respectively.

https://colorhunt.co/palette/3a10784e31aa2f58cd3795bd
https://colorhunt.co/palette/c3ba85dad5abf0f0cbfeffe2

**Comment by meenbeese** [comment]
> When I scale the image down to something that Is more indicative of "app icon size" I think the contrast and pop is good.

I will trust your judgement on that as I did not test it myself. It probably looks good and I am just nitpicking.

> That being said if we want to rework the colors completely, I'd suggest the following palettes for the "onion" and "purple" colors respectively.

These resources look nice indeed! They can be very well used in a redesign if need be in the future.

**Comment by hax0rbana-adam** [comment]
> Btw using a more popping color is a good idea too that didn't immediately occur to me.

Heh, well I still credit you for the idea of using more "contrasting colors and backgrounds". :smiley: 

And my bad on the size, I didn't realize the rendered version was so large until after I posted it. Here's a scaled down version of the same thing.

orbot-no-shadow-deep-purple-background_small

I think it looks less eye popping when rendered at normal icon size.

**Comment by n8fr8** [comment]
We are still keeping the pre-v17 icon for now, as we transition users to the new design. We had feedback that changing the icon without warning caused confusion and concern for users in high risk, high anxiety context. I appreciate the work making this new vector icon, and am glad to merge your effort here.

Our new "Orbi" mascot and design is staying, and we'll settle on a new icon for both the Android and iOS apps soon, and when we do, we will make sure to make it vector like this.

**Comment by QW21WQ** [comment]
@n8fr8 i hope you will NOT delete new mascot. hax0rbana-adam’s idea got plenty of dislikes:
IMG_0631

We like mascot. So… I hope it won’t be deleted

**Comment by beedell-roke** [comment]
@n8fr8, should this also replace the `README`'s icon?

https://github.com/guardianproject/orbot-android/blob/bc3f48eeb74f165ec9d59cfedfd536008f313fb1/README.md?plain=1#L3

**Pull request merged**
