### PR TITLE
Delete unused TCPSourceApp file in service

### PR DESCRIPTION
**Pull request by meenbeese**
I noticed that the file was not being used (or even mentioned) anywhere, so I deleted it.
Many of its methods and properties were also not used and were caught in linting.

Tested on Pixel 6a API 34.

### CODE REVIEW

**Comment by bitmold** [comment]
```
commit efb1c0686d0e7a80b7470020d748be4d0814d7e4
Author: n8fr8 <nathan@guardianproject.info>
Date:   Wed Sep 4 17:07:12 2019 -0400

    implement initial framework for blocking traffic per app
    - also add ability to disable tor routing as a per app preference

```

I think this was part of some older @n8fr8 effort  had to block internet traffic from a given app (a feature I still want to see one day!) 

You're right @meenbeese that it's unused (and so won't compile into the app) but I wonder if there's anyting in here worth salvaging before just deleting it..?

**Comment by meenbeese** [comment]
I don't personally see much value in keeping a half-baked implementation of a new feature. It creates unnecessary clutter and noise in the master branch. What might make more sense is to create a new branch where the file can be transferred. This way, we won't be completely deleting it and keeping it for future use. WDYT?

**Comment by bitmold** [comment]
I think it doesn't really matter all that much one way or the other

since you asked, I think if anyone's understanding of a project is conceptually impeded by the one off existence of an extra file to such an extent that they're not able to see the forest from the trees then they can't meaningfully interact w the codebase anyway

code can always be leaner, but still at the end of the day a codebase (and its leanness) doesn't exist in a vacuum. doing things like deleting or renaming files may optimize a project in one sense, but those ver samey gesture can then go and obscure a project's history, context and overall domain knowledge in another

From time to time I do housekeeping on this project and agree that code leanness is pretty important. But still, throughout any codebase's lifespan there will basically always be chunks of uninvoked methods or commented out code that lingers because it provides knowledge about the project in its own right. Erasing or obscuring that knowledge can sometimes be its own kind of clutter

-------- Message d'origine --------
Le 18 déc. 2023, 10:57 PM, Meenbeese < ***@***.***> a écrit :
I don't personally see much value in keeping a half-baked implementation of a new feature. It creates unnecessary clutter and noise in the master branch. What might make more sense is to create a new branch where the file can be transferred. This way, we won't be completely deleting it and keeping it for future use. WDYT?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/guardianproject/orbot/pull/1040#issuecomment-1862077136">https://github.com/guardianproject/orbot/pull/1040#issuecomment-1862077136", "url": "[https://github.com](<a href=)/guardianproject/orbot/pull/1040#issuecomment-1862077136">https://github.com/guardianproject/orbot/pull/1040#issuecomment-1862077136", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by meenbeese** [comment]
I understand your perspective on keeping the file. As I mentioned earlier, one approach could be to create a separate branch for this file. This way, if you see value in it and want to revisit it in the future, it’s there for you. However, I still believe that we should strive to keep our main branch as clutter-free as possible to maintain the project’s cleanliness and efficiency. But, at the end of the day, you don't have to accept the PR if you disagree. Let me know what you think.

**Comment by bitmold** [comment]
Sorry for phone email typos, meant to say "those very same gestures" 

My point was that letting this one quiet file (which does not compile into the project anyway since it's unreferenced) sit  in some dark corner of the project is so much leaner than introducing a new branch and keeping track of that branch. If this isolated file truly gets in the way of a contributor's ability to interact with the codebase then I'm suspicious of their ability to engage with the code in a way that's helpful or productive in the first place. 

I really appreciate your wanting to keep this project tidy but I'm dying on this hill because it has a wonderful view. 

There's a lot of things in Orbot that don't quite work properly, sometimes if you click on a bunch of stuff really fast you can cause the app to crash. When I emerge from my reclusion to contribute to this project, it's those issues that I prioritize addressing over leanness. There's a lot that doesn't work or that gets broken, the thing I'd appreciate the most is you or any other contributor for that matter looking in those places to make things run smooth and properly.

**Pull request closed without merging**
