### PR TITLE
Minor fix to README.md

### PR DESCRIPTION
**Pull request by meenbeese**
Updated the copyright text to match the current year and made it bold to show importance and increase visibility.

### CODE REVIEW

**Comment by bitmold** [comment]
THanks

**Comment by meenbeese** [comment]
I don't understand. Why was the PR closed?

**Comment by bitmold** [comment]
Yes, it was an accident. I didn't have coffee and the github user interface leaves a lot to be desired...

**Comment by n8fr8** [comment]
@meenbeese that said, I'm usually not a fan of merging tiny formatting changes like this into projects. I appreciate you are perhaps taking your first steps in committing code to open-source projects, and trying to learn the protocols and process. 

If you want to make an actual contribution, take on something a bit larger and more meaningful. Fix a bug, improve our code comments, add a localization, clean-up our gradle files... there are many useful things you can do beyond fixing *copyright* text on a freely licensed open-source project. ahem.

**Comment by meenbeese** [comment]
@n8fr8 That's a fair suggestion. I am planning to learn Android app development soon. Hope I can help more then.

**Pull request merged**
