### PR TITLE
Fix #501 - Duplicate Config Info in Build Files

### LINKED ISSUE #501: Duplicate Config Info in Build Files
There is a lot of duplication of code in the build files. This makes it harder to manage dependencies and configurations.

### PR DESCRIPTION
**Pull request by sisbell**
Changes
* Upgraded gradle from 6.7.1 -> 7.0.2
* Cleaned up and reordered dependencies in lexical order
* Added the following gradle build files to remove duplication

1. commons.gradle - all projects
2. commons-device.gradle - Applies across android app modules: {app, app-mini, app-tv}
3. commons-limited-device.gradle - Applies across android app module with limited capabilities: {app-mini, app-tv}

Upgrade dependency versions

- 'androidx.core:core-ktx:1.5.0' -> 1.6.0
-  'androidx.appcompat:appcompat:1.3.0' -> 1.3.1'
- 'androidx.test.ext:junit:1.1.2' -> 1.1.3
- 'androidx.test.espresso:espresso-core:3.3.0' -> 3.4.0
- 'androidx.constraintlayout:constraintlayout:2.0.4' -> 2.1.0
- "androidx.leanback:leanback-paging:1.1.0-alpha07" -> 1.1.0-alpha08
- 'androidx.recyclerview:recyclerview:1.1.0' -> 1.2.
- 'com.google.android.material:material:1.2.1' -> 1.4.0
- kotlin: 1.4.32 -> 1.5.20
- leanback: 1.1.0-rc01 -> 1.2.0-alpha01

Build Issues
I found that the command line build on master fails on a lint error for orbotservice: I turned off abortOnError for orbotserivice n the 501 branch for now to get the build working. This will be another issue.

Verified build works in Android Studio 2020.3.1 and on command line on Mac. Ran the main app in emulator successfully. Did not test app functionality for mini or TV.

### CODE REVIEW

**Comment by sisbell** [comment]
Also upgraded JDK from 8 to 11

**Comment by sisbell** [comment]
Need MR #504 merged before this MR.

**Comment by syphyr** [comment]
The build output does not properly name the apk files using "git describe --tags --always" after this change.  The output apk file names look like this now: Orbot-null-fullperm-arm64-v8a-release.apk (when it should look like Orbot-16.5.1-BETA-2a-tor.0.4.5.9-fullperm-arm64-v8a-release.apk)

**Comment by syphyr** [comment]
Since getVersionName() is only used in one location (app/build.gradle), it doesn't really need to be separated out into commons-device.gradle.  This fixes the naming issue with the apk files: https://github.com/syphyr/orbot/commit/a5aa9e1d74cb8531464f4f1000dbe49aa39d966a

**Comment by sisbell** [comment]
I'm seeing in the logs

```
WARNING:API 'ApkVariantOutput.getVersionCodeOverride()' is obsolete and has been replaced with 'VariantOutput.versionCode()'.
It will be removed in version 7.0 of the Android Gradle plugin.
Gradle Properties must be used to change Variant information.
For more information, see https://d.android.com/r/tools/use-properties.
```
I think this is the problem.

**Comment by sisbell** [comment]
@syphyr If moving the getVersionName fixes the problem, I'm not sure what the affect is for the obsolete getVersionCodeOverride. Is this being used for anything?

**Comment by syphyr** [comment]
getVersionCodeOverride does not seem to be used anywhere.

**Comment by sisbell** [comment]
@syphyr Good catch. From what I can determine, the problem is that I'm creating ext.getVersionName. It's getting overridden by ApkVariant.getVersionName, an internal Gradle api, which returns null. So using the original def function avoids a conflict, so it works.

**Comment by syphyr** [comment]
For some reason, https://github.com/guardianproject/orbot/pull/502/commits/11a593875cca50d8ad72882b1e3d8305f7b1ddb0 and https://github.com/guardianproject/orbot/pull/502/commits/92693d6691f86d872456458ee8289c92d431e201 cause an installation error when installing the apk file.  It builds successfully with these two changes, but the apk will not install.

**Comment by sisbell** [comment]
@sysphr Are you seeing an ABI error on install? I missed generating the universal apk. I just added the commit. I can install and run that one.

**Comment by syphyr** [comment]
I added the fix for generating the universal apk, but that did not make any difference.  The installation just keeps saying the installer is corrupted.  This is the logcat:

```
08-02 19:13:05.048   928 22008 I ActivityManager: Start proc 6519:com.android.packageinstaller/u0a19 for activity com.android.packageinstaller/.PackageInstallerActivity
08-02 19:13:05.116  6519  6519 W System  : ClassLoader referenced unknown path: /system/priv-app/PackageInstaller/lib/arm64
08-02 19:13:05.288   928  1080 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
08-02 19:13:05.357  6519  6535 I Adreno  : QUALCOMM build                   : 422eead, I8e707a60c0
08-02 19:13:05.357  6519  6535 I Adreno  : Build Date                       : 11/23/17
08-02 19:13:05.357  6519  6535 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
08-02 19:13:05.357  6519  6535 I Adreno  : Local Branch                     : mybranch29262620
08-02 19:13:05.357  6519  6535 I Adreno  : Remote Branch                    : quic/LA.BR.1.3.6.c2_rb2.28
08-02 19:13:05.357  6519  6535 I Adreno  : Remote Branch                    : NONE
08-02 19:13:05.357  6519  6535 I Adreno  : Reconstruct Branch               : NOTHING
08-02 19:13:05.387  6519  6535 I OpenGLRenderer: Initialized EGL, version 1.4
08-02 19:13:05.387  6519  6535 D OpenGLRenderer: Swap behavior 1
08-02 19:13:05.435   928   949 I ActivityManager: Displayed com.android.packageinstaller/.PackageInstallerActivity: +400ms
08-02 19:13:05.460  6519  6519 W PackageParser: Unknown element under <manifest>: queries at /data/user_de/0/com.android.packageinstaller/cache/package1439910176.apk Binary XML file line #30
08-02 19:13:05.494  6519  6519 I AppSecurityPermissions: Ignoring unknown permission:android.permission.FOREGROUND_SERVICE
08-02 19:13:07.402   928 24186 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.android.packageinstaller/cache/package1439910176.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10019 on display 0
08-02 19:13:07.469  6519  6519 W InstallAppProgress: Replacing package:org.torproject.android
08-02 19:13:07.498   928 22008 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
08-02 19:13:07.547   405   405 I         : free_cache(13716976) avail 14117142528
08-02 19:13:07.611   928   949 I ActivityManager: Displayed com.android.packageinstaller/.InstallAppProgress: +196ms
08-02 19:13:07.631  6519  6535 D OpenGLRenderer: endAllActiveAnimators on 0x7f90cdb800 (RippleDrawable) with handle 0x7fa75abc00
08-02 19:13:08.535   928   954 W PackageManager: Downgrade detected: Update version code 1651100210 is older than current 1651100212
08-02 19:13:08.567  6519  6519 D InstallAppProgress: Installation error code: 4
08-02 19:13:09.870   381   381 I MSM-irqbalance: Decided to move IRQ240 from CPU1 to CPU3
```

**Comment by syphyr** [comment]
Ahh, the problem is with the upgrade.  If I uninstall the previous version, then the new version installs without errors.  The issue must be this:

PackageManager: Downgrade detected: Update version code 1651100210 is older than current 1651100212

**Comment by sisbell** [comment]
@syphyr right I also got that upgrade error at first. I also noticed the version in the filename for the main apk is orbot-tv-1.0.0. This is the latest tag. Should this be opened as another issue?

**Comment by syphyr** [comment]
I'm not sure where "orbot-tv" is getting its version number (I never really checked before this), but it seems like a separate issue.  Also, I'm still trying to figure out where version code 1651100212 was defined with the previously installed version.

**Comment by syphyr** [comment]
The versionName is hardcoded for orbot-tv in app-tv/build.gradle, so that explains that.  Orbot-tv seems like it should also be using the latest git tag for the versionName, but maybe there is a reason for this.

**Comment by syphyr** [comment]
Oh, I understand now. Removing the "unused build code for version overrides" is what bumped the version code to 1651100212.  I'm not sure if its a good idea to remove those "version overrides" since it actually IS being used and it breaks the upgrade process by removing it.

**Comment by sisbell** [comment]
It looks like that specific version override method is deprecated in android tools plugin 7. But the version can still be set another way. I'll investigate.

**Comment by sisbell** [comment]
@syphyr I added in the ABI version code logic. I put it into commons-device so its only defined once. I verified that the manifest versionCode matches in the apk files. I'm not aware of any more issues with this MR.

**Comment by syphyr** [comment]
I don't see any more issues either after latest change.  Good job.

**Comment by n8fr8** [comment]
Thanks for all the effort and detective work here. Reviewing and testing.

**Pull request merged**
