### PR TITLE
Rewrite OnionServiceDeleteDialogFragment in Kotlin

### PR DESCRIPTION
**Pull request by meenbeese**
Continues the Kotlin rewrite with the Onion Service.

Tested on Pixel 8 API 34.

### CODE REVIEW

**Comment by bitmold** [comment]
Looks good, but wondering if you have you used this code to delete an onion service and have seen the functionality to be the same?

**Comment by bitmold** [comment]
Cool thanks! If you're up for it, it'd be cool to have this screen use an empty view for when there are no user/app services being listed..

**Comment by meenbeese** [comment]
Thanks for the feedback, you mean a placeholder text/image like this, right? I was already planning to improve the UI by replacing the radio buttons with segmented buttons and this can be a nice addition to that.

**Comment by bitmold** [comment]
Yup, that's what I meant !

**Pull request merged**
